#!/usr/bin/env bash
#prints in while

var=1
while [ $var -le 100 ]
do
    ex1=$((var % 3))
    ex2=$((var % 5))
    if [ $ex1 == 0 ] && [ $ex2 == 0 ]
    then
        echo "FizzBuzz"
    elif [ $ex1 == 0 ] && [ $ex2 != 0 ]
    then
        echo "Fizz"
    elif [ $ex1 != 0 ] && [ $ex2 == 0 ]
    then
        echo "Buzz"
    else
    echo $var
    fi
    var=$((var + 1))
done
